[package]
name = "dankgine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "dankgine"
path = "src/lib.rs"
crate-type = ["lib","cdylib"]

[dependencies]
wasm-bindgen = "0.2.80"
